### ISSUE TITLE
Render problem in NextJS when using Chakra UI's Drawer component

### ISSUE THREAD

**Issue by felipesses** [rive-app/rive-react#164]
Hi, I am using NextJs and Chakra UI in my project and I'm having some issues with the Rive Component. Here's the issue:

https://user-images.githubusercontent.com/45373166/227381543-24c70f76-12a9-4c49-a4f0-fd8a083850c6.mov

When I close the Drawer and open it again, the canvas height and width are setting to 0px automatically

before:
![Captura de Tela 2023-03-22 às 10 49 37](https://user-images.githubusercontent.com/45373166/226924851-326e9f93-0c76-4f64-9597-f259993331e0.png)

after closing and reopening:
![Captura de Tela 2023-03-22 às 10 50 08](https://user-images.githubusercontent.com/45373166/226924978-735ea15e-9433-4130-adf3-3d0688c683bc.png)

This is happening with other .riv files aswell.

**Comment by NullEnt1ty** [comment]
I can observe the same behaviour when using the [Popover](https://chakra-ui.com/docs/components/popover/usage) component from Chakra UI with the prop `isLazy`. By default it only renders the popover content when it is open. The content container get's removed from DOM when the popover is closed. This seems to be the culprit here.

I can tell Chakra UI to keep the container mounted after the popover was initially opened (using `lazyBehavior="keepMounted"`). This fixes the problem and serves as a workaround for me at the moment (though it's not ideal when you need the unmounting behaviour to save performance).

Unfortunately, the Drawer component doesn't seem to have such prop according to the docs 😕.

**Comment by felipesses** [comment]
> I can observe the same behaviour when using the [Popover](https://chakra-ui.com/docs/components/popover/usage) component from Chakra UI with the prop `isLazy`. By default it only renders the popover content when it is open. The content container get's removed from DOM when the popover is closed. This seems to be the culprit here.
> 
> I can tell Chakra UI to keep the container mounted after the popover was initially opened (using `lazyBehavior="keepMounted"`). This fixes the problem and serves as a workaround for me at the moment (though it's not ideal when you need the unmounting behaviour to save performance).
> 
> Unfortunately, the Drawer component doesn't seem to have such prop according to the docs 😕.

thanks for the reply! do you have any possible workaround or ideas that I could try?
